---

- name: hostconfig | preflight check
  hosts: localhost
  gather_facts: false
  tasks:
    - assert: { that: "ansible_version.full is version_compare('2.9', '>=')", msg: "Ansible >=2.9 required." }
    - assert: { that: "os_id is defined and os_id != ''", msg: "Please define os_id" }
    - assert: { that: "targethost is defined and targethost != ''", msg: "Please define targethost" }

- name: hostconfig | configure the host
  hosts: "{{targethost}}"
  tasks:
    - include_role:
        name: "hostconfig"
